//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxCredit.Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TaxCredit.Core.Models;
    
    public partial class EliteTaxCreditEntities : DbContext
    {
        public EliteTaxCreditEntities()
            : base("name=EliteTaxCreditEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tcAGMI> tcAGMIs { get; set; }
        public virtual DbSet<tcAsset> tcAssets { get; set; }
        public virtual DbSet<tcBuilding> tcBuildings { get; set; }
        public virtual DbSet<tcComplianceEntity> tcComplianceEntities { get; set; }
        public virtual DbSet<tcComplianceEntityRelationship> tcComplianceEntityRelationships { get; set; }
        public virtual DbSet<tcComplianceEntityType> tcComplianceEntityTypes { get; set; }
        public virtual DbSet<tcComplianceProgram> tcCompliancePrograms { get; set; }
        public virtual DbSet<tcComplianceRentRestrictionIncomeLimit> tcComplianceRentRestrictionIncomeLimits { get; set; }
        public virtual DbSet<tcComplianceRule> tcComplianceRules { get; set; }
        public virtual DbSet<tcComplianceRuleTarget> tcComplianceRuleTargets { get; set; }
        public virtual DbSet<tcDelinquentRentColumn> tcDelinquentRentColumns { get; set; }
        public virtual DbSet<tcDTAlarm> tcDTAlarms { get; set; }
        public virtual DbSet<tcDTAsset> tcDTAssets { get; set; }
        public virtual DbSet<tcDTBuilding> tcDTBuildings { get; set; }
        public virtual DbSet<tcDTBuildingComplianceReport> tcDTBuildingComplianceReports { get; set; }
        public virtual DbSet<tcDTEligibility> tcDTEligibilities { get; set; }
        public virtual DbSet<tcDTFamily> tcDTFamilies { get; set; }
        public virtual DbSet<tcDTFamilyMember> tcDTFamilyMembers { get; set; }
        public virtual DbSet<tcDTFamilyMemberStatu> tcDTFamilyMemberStatus { get; set; }
        public virtual DbSet<tcDTIncome> tcDTIncomes { get; set; }
        public virtual DbSet<tcDTIncomeType> tcDTIncomeTypes { get; set; }
        public virtual DbSet<tcDTMedianIncome> tcDTMedianIncomes { get; set; }
        public virtual DbSet<tcDTMinimumIncomeLimit> tcDTMinimumIncomeLimits { get; set; }
        public virtual DbSet<tcDTMinimumSetAsideType> tcDTMinimumSetAsideTypes { get; set; }
        public virtual DbSet<tcDTProperty> tcDTProperties { get; set; }
        public virtual DbSet<tcDTPropertyComplianceReport> tcDTPropertyComplianceReports { get; set; }
        public virtual DbSet<tcDTRentRestrictionIncomeLimit> tcDTRentRestrictionIncomeLimits { get; set; }
        public virtual DbSet<tcDTSpecialStatu> tcDTSpecialStatus { get; set; }
        public virtual DbSet<tcDTStudentStatu> tcDTStudentStatus { get; set; }
        public virtual DbSet<tcDTTIC> tcDTTICs { get; set; }
        public virtual DbSet<tcDTTransactionType> tcDTTransactionTypes { get; set; }
        public virtual DbSet<tcDTUnit> tcDTUnits { get; set; }
        public virtual DbSet<tcEliteKeyMap> tcEliteKeyMaps { get; set; }
        public virtual DbSet<tcFamily> tcFamilies { get; set; }
        public virtual DbSet<tcFamilyMember> tcFamilyMembers { get; set; }
        public virtual DbSet<tcFamilyMemberStatu> tcFamilyMemberStatus { get; set; }
        public virtual DbSet<tcGender> tcGenders { get; set; }
        public virtual DbSet<tcHistoricalOccupancy> tcHistoricalOccupancies { get; set; }
        public virtual DbSet<tcIncome> tcIncomes { get; set; }
        public virtual DbSet<tcIncomeType> tcIncomeTypes { get; set; }
        public virtual DbSet<tcMedianIncome> tcMedianIncomes { get; set; }
        public virtual DbSet<tcMinimumIncomeLimit> tcMinimumIncomeLimits { get; set; }
        public virtual DbSet<tcMinimumSetAsideType> tcMinimumSetAsideTypes { get; set; }
        public virtual DbSet<tcMoveInTemp> tcMoveInTemps { get; set; }
        public virtual DbSet<tcOccupancy> tcOccupancies { get; set; }
        public virtual DbSet<tcProperty> tcProperties { get; set; }
        public virtual DbSet<tcRent> tcRents { get; set; }
        public virtual DbSet<tcRole> tcRoles { get; set; }
        public virtual DbSet<tcSetting> tcSettings { get; set; }
        public virtual DbSet<tcSpecialStatu> tcSpecialStatus { get; set; }
        public virtual DbSet<tcStudentStatu> tcStudentStatus { get; set; }
        public virtual DbSet<tcTIC> tcTICs { get; set; }
        public virtual DbSet<tcTransactionType> tcTransactionTypes { get; set; }
        public virtual DbSet<tcUniqueKeyMap> tcUniqueKeyMaps { get; set; }
        public virtual DbSet<tcUnit> tcUnits { get; set; }
        public virtual DbSet<tcUnitSize> tcUnitSizes { get; set; }
        public virtual DbSet<tcUser> tcUsers { get; set; }
        public virtual DbSet<tcUsersRole> tcUsersRoles { get; set; }
        public virtual DbSet<tcRentRestrictionPercent> tcRentRestrictionPercents { get; set; }
    }
}
